# Generated by Django 2.1.4 on 2019-02-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_auto_20190130_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressType', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120)),
                ('addressLine1', models.CharField(max_length=120)),
                ('addressLine2', models.CharField(blank=True, max_length=120, null=True)),
                ('addressCity', models.CharField(max_length=120)),
                ('addressCountry', models.CharField(default='United States', max_length=120)),
                ('addressState', models.CharField(max_length=120)),
                ('addressPostalCode', models.CharField(max_length=120)),
                ('addressBillingProfile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.BillingProfile')),
            ],
        ),
    ]
