# Generated by Django 2.1.7 on 2019-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_address_addressactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
