# Generated by Django 2.1.4 on 2019-02-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestEmail', models.EmailField(max_length=254)),
                ('guestActive', models.BooleanField(default=True)),
                ('guestDateLastUpdated', models.DateTimeField(auto_now=True)),
                ('guestDateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
