# Generated by Django 2.1.7 on 2019-02-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guestSendPromos',
            field=models.BooleanField(default=True),
        ),
    ]
