# Generated by Django 2.1.7 on 2019-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guest_guestsendpromos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guestSendPromos',
            field=models.BooleanField(default=False),
        ),
    ]
