# Generated by Django 2.1.4 on 2019-02-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_card_carddefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeStripeID', models.CharField(max_length=120)),
                ('chargePaid', models.BooleanField(default=False)),
                ('chargeRefunded', models.BooleanField(default=False)),
                ('chargeOutcome', models.TextField(blank=True, max_length=255, null=True)),
                ('chargeOutcomeType', models.CharField(blank=True, max_length=120, null=True)),
                ('chargeSellerMessage', models.CharField(blank=True, max_length=120, null=True)),
                ('chargeRiskLevel', models.CharField(blank=True, max_length=120, null=True)),
                ('billingProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
            options={
                'db_table': 'charge',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='cardDefault',
            field=models.BooleanField(default=True),
        ),
    ]
