# Generated by Django 2.1.4 on 2019-02-21 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20190221_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardDateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
