# Generated by Django 2.1.7 on 2019-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20190221_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardAddressLine1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardAddressLine2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardCity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardPostalCode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardState',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
