# Generated by Django 2.1.7 on 2019-02-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20190224_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='profileType',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User')], default='guest', max_length=120),
            preserve_default=False,
        ),
    ]
