# Generated by Django 2.1.4 on 2019-01-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_productslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('pricingID', models.AutoField(primary_key=True, serialize=False)),
                ('pricingBasePrice', models.DecimalField(decimal_places=3, max_digits=8)),
                ('pricingDateCreated', models.DateTimeField(verbose_name='date created')),
                ('pricingStartDate', models.DateTimeField(verbose_name='start date')),
                ('pricingEndDate', models.DateTimeField(verbose_name='end date')),
                ('pricingNote', models.TextField(max_length=200)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'pricing',
            },
        ),
    ]
