# Generated by Django 2.1.4 on 2019-01-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productslug'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDiscount',
            fields=[
                ('cDiscountID', models.AutoField(primary_key=True, serialize=False)),
                ('cDiscountName', models.CharField(max_length=40)),
                ('cDiscountDescription', models.TextField(max_length=200)),
                ('cDiscountType', models.CharField(max_length=30)),
                ('cDiscountAmount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cDiscountDateCreated', models.DateTimeField(verbose_name='date created')),
                ('cDiscountDateValidFrom', models.DateTimeField(verbose_name='date created')),
                ('cDiscountDateValidUntil', models.DateTimeField(verbose_name='date created')),
                ('cDiscountCouponCode', models.CharField(max_length=20)),
                ('cDiscountMaxDiscount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cDiscountMinOrderValue', models.DecimalField(decimal_places=3, max_digits=8)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
            options={
                'db_table': 'cdiscount',
            },
        ),
        migrations.CreateModel(
            name='PDiscount',
            fields=[
                ('pDiscountID', models.AutoField(primary_key=True, serialize=False)),
                ('pDiscountName', models.CharField(max_length=40)),
                ('pDiscountDescription', models.TextField(max_length=200)),
                ('pDiscountType', models.CharField(max_length=30)),
                ('pDiscountAmount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('pDiscountDateCreated', models.DateTimeField(verbose_name='date created')),
                ('pDiscountDateValidFrom', models.DateTimeField(verbose_name='date created')),
                ('pDiscountDateValidUntil', models.DateTimeField(verbose_name='date created')),
                ('pDiscountCouponCode', models.CharField(max_length=20)),
                ('pDiscountMaxDiscount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('pDiscountMinOrderValue', models.DecimalField(decimal_places=3, max_digits=8)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'pdiscount',
            },
        ),
    ]
