# Generated by Django 2.1.4 on 2019-01-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdiscount',
            name='cDiscountMaxDiscount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cdiscount',
            name='cDiscountMinOrderValue',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cdiscount',
            name='cDiscountValue',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pdiscount',
            name='pDiscountMaxDiscount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pdiscount',
            name='pDiscountMinOrderValue',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pdiscount',
            name='pDiscountValue',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricingBasePrice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
