# Generated by Django 2.1.4 on 2019-01-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_cdiscount_pdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdiscount',
            name='pDiscountDateValidFrom',
            field=models.DateTimeField(verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='pdiscount',
            name='pDiscountDateValidUntil',
            field=models.DateTimeField(verbose_name='valid until'),
        ),
    ]
