# Generated by Django 2.1.4 on 2019-01-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20190118_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdiscount',
            name='cDiscountDateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='cdiscount',
            name='cDiscountDateValidFrom',
            field=models.DateTimeField(verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='cdiscount',
            name='cDiscountDateValidUntil',
            field=models.DateTimeField(verbose_name='valid until'),
        ),
        migrations.AlterField(
            model_name='pdiscount',
            name='pDiscountDateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
