# Generated by Django 2.1.4 on 2019-01-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricing_pricingisactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='pricingStartDate',
            new_name='pricingValidFrom',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='pricingEndDate',
            new_name='pricingValidUntil',
        ),
        migrations.AddField(
            model_name='pdiscount',
            name='pDiscountIsActive',
            field=models.BooleanField(default=False),
        ),
    ]
