# Generated by Django 2.1.4 on 2019-01-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20190118_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdiscount',
            old_name='cDiscountAmount',
            new_name='cDiscountValue',
        ),
        migrations.RenameField(
            model_name='pdiscount',
            old_name='pDiscountAmount',
            new_name='pDiscountValue',
        ),
    ]
