# Generated by Django 2.1.4 on 2019-02-01 23:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20190131_2303'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pdiscount',
            managers=[
                ('largestActive', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='cdiscount',
            name='cDiscountIsActive',
            field=models.BooleanField(default=False),
        ),
    ]
