# Generated by Django 2.1.4 on 2019-02-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20190201_2340'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pdiscount',
            managers=[
            ],
        ),
    ]
