# Generated by Django 2.1.4 on 2019-01-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20190119_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='pricingDateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
