# Generated by Django 2.1.4 on 2019-02-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_auto_20190202_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdiscount',
            name='cDiscountType',
            field=models.CharField(choices=[('Percent', 'Percent'), ('Amount', 'Amount')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pdiscount',
            name='pDiscountType',
            field=models.CharField(choices=[('Percent', 'Percent'), ('Amount', 'Amount')], max_length=30),
        ),
    ]
