# Generated by Django 2.1.4 on 2019-02-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20190203_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDiscount',
            fields=[
                ('sDiscountID', models.AutoField(primary_key=True, serialize=False)),
                ('sDiscountName', models.CharField(max_length=40)),
                ('sDiscountDescription', models.TextField(max_length=200)),
                ('sDiscountMessage', models.CharField(max_length=150)),
                ('sDiscountType', models.CharField(choices=[('Percent', 'Percent'), ('Amount', 'Amount')], max_length=30)),
                ('sDiscountValue', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sDiscountDateCreated', models.DateTimeField(verbose_name='date created')),
                ('sDiscountDateValidFrom', models.DateTimeField(verbose_name='date created')),
                ('sDiscountDateValidUntil', models.DateTimeField(verbose_name='date created')),
                ('sDiscountCouponCode', models.CharField(max_length=20)),
                ('sDiscountMaxAmount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sDiscountMinSaleValue', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sDiscountAutomatic', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sdiscount',
            },
        ),
        migrations.CreateModel(
            name='SDiscountCondition',
            fields=[
                ('sDCID', models.AutoField(primary_key=True, serialize=False)),
                ('sDCName', models.CharField(max_length=50)),
                ('sDCDescription', models.TextField(max_length=200)),
                ('sDCType', models.CharField(choices=[('Sale', 'Sale'), ('Item', 'Item'), ('User', 'User')], max_length=50)),
                ('sDCFieldName', models.CharField(choices=[('saleSubTotal', 'Sale Sub-Total'), ('productCategories', 'Product Category'), ('productName', 'Product Name')], max_length=50)),
                ('sDCCompareOperator', models.CharField(choices=[('equal_to', 'Is equal to'), ('greater_than', 'Is greater than'), ('less_than', 'Is less than')], max_length=50)),
                ('sDCValue', models.CharField(max_length=70)),
                ('sDCNumRequired', models.IntegerField(default=1)),
                ('sDiscountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.SDiscount')),
            ],
            options={
                'db_table': 'sdiscount_condition',
            },
        ),
    ]
