# Generated by Django 2.1.4 on 2019-02-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_sdiscount_sdiscountcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdiscount',
            name='sDiscountIsShippingDiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sdiscount',
            name='sDiscountDateValidFrom',
            field=models.DateTimeField(verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='sdiscount',
            name='sDiscountDateValidUntil',
            field=models.DateTimeField(verbose_name='valid until'),
        ),
    ]
