# Generated by Django 2.1.4 on 2019-02-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20190206_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdiscount',
            name='sDiscountIsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sdiscount',
            name='sDiscountCouponCode',
            field=models.CharField(max_length=20, verbose_name='coupon code'),
        ),
    ]
