# Generated by Django 2.1.4 on 2019-02-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_auto_20190206_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdiscountcondition',
            old_name='sDCDescription',
            new_name='sDCFailMessage',
        ),
    ]
