# Generated by Django 2.1.4 on 2019-01-25 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitems',
            name='piColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Color'),
        ),
    ]
