# Generated by Django 2.1.4 on 2019-01-30 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20190121_2314'),
        ('purchases', '0002_auto_20190125_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Purchase',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='transactionDate',
            new_name='purchaseDate',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='transactionID',
            new_name='purchaseID',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='transactionNote',
            new_name='purchaseNote',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='transactionStatus',
            new_name='purchaseStatus',
        ),
        migrations.RenameField(
            model_name='purchaseitems',
            old_name='transactionID',
            new_name='purchaseID',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
