# Generated by Django 2.1.4 on 2019-01-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20190130_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='transactionTypeID',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
