# Generated by Django 2.1.4 on 2019-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchaseitems_piisavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitems',
            name='piBarcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes'),
        ),
    ]
