# Generated by Django 2.1.7 on 2019-02-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20190208_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitems',
            name='piSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
    ]
