# Generated by Django 2.1.7 on 2019-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigHomePageImage',
            fields=[
                ('bigHomePageImageID', models.AutoField(primary_key=True, serialize=False)),
                ('bigHomePageImagePath', models.ImageField(upload_to='homepage')),
                ('bigHomePageImageAltText', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'big_home_page_image',
            },
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('homePageImageID', models.AutoField(primary_key=True, serialize=False)),
                ('homePageImagePath', models.ImageField(upload_to='homepage')),
                ('homePageImageAltText', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'home_page_image',
            },
        ),
    ]
