# Generated by Django 2.1.7 on 2019-02-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bighomepageimage',
            name='bigHomePageImageLink',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='homePageImageLink',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
