# Generated by Django 2.1.4 on 2019-02-09 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('jurisdictionID', models.AutoField(primary_key=True, serialize=False)),
                ('jurisdictionLabel', models.CharField(max_length=70)),
                ('jurisdictionState', models.CharField(blank=True, max_length=50, null=True)),
                ('jurisdictionCity', models.CharField(blank=True, max_length=50, null=True)),
                ('jurisdictionZip', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'jurisdiction',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('taxRateID', models.AutoField(primary_key=True, serialize=False)),
                ('taxRateName', models.CharField(max_length=50)),
                ('taxRateMultiplier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxRateDateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('taxRateValidFrom', models.DateTimeField(verbose_name='start date')),
                ('taxRateValidUntil', models.DateTimeField(verbose_name='end date')),
                ('taxRateNote', models.TextField(max_length=200)),
                ('taxRateIsActive', models.BooleanField(default=False)),
                ('jurisdictionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.Jurisdiction')),
            ],
            options={
                'db_table': 'tax_rate',
            },
        ),
    ]
