# Generated by Django 2.1.4 on 2019-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='taxRateMultiplier',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
