# Generated by Django 2.1.4 on 2019-02-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0011_auto_20190211_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('parcelID', models.AutoField(primary_key=True, serialize=False)),
                ('parcelName', models.CharField(max_length=120)),
                ('parcelWeight', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'parcel',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('shipmentDateCreated', models.DateTimeField(verbose_name='shipment date created')),
                ('shipmentNote', models.CharField(default='Default Shipment Note', max_length=120)),
                ('shipmentFromAddress', models.CharField(max_length=120)),
                ('shipmentToAddress', models.CharField(max_length=120)),
                ('shipmentLabelIsBought', models.BooleanField(default=False)),
                ('shipmentCarrier', models.CharField(max_length=120)),
                ('shipmentRate', models.CharField(max_length=120)),
                ('shipmentCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shipmentTrackingNumber', models.CharField(max_length=120)),
                ('saleID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Sale')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='shipmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.Shipment'),
        ),
    ]
