# Generated by Django 2.1.4 on 2019-02-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipmentFromAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipmentFromAddress', to='addresses.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipmentToAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipmentToAddress', to='addresses.Address'),
        ),
    ]
