# Generated by Django 2.1.4 on 2019-02-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_addresseasypostid'),
        ('shipping', '0003_auto_20190211_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseID', models.AutoField(primary_key=True, serialize=False)),
                ('warehouseName', models.CharField(max_length=120)),
                ('warehouseAddress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Address')),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipmentTrackingNumber',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouseID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipping.Warehouse'),
        ),
    ]
