# Generated by Django 2.1.4 on 2019-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_auto_20190211_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipmentEasyPostID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
