# Generated by Django 2.1.4 on 2019-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shipment_shipmenteasypostid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipmentStatus',
            field=models.CharField(choices=[('in progress', 'Being Prepared.'), ('printed', 'Being Prepared.'), ('shipped', 'Shipped')], default='in progress', max_length=120),
        ),
    ]
