# Generated by Django 2.1.4 on 2019-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_shipment_shipmentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipmentStatus',
            field=models.CharField(choices=[('in progress', 'Being Prepared.'), ('printed', 'Printed'), ('shipped', 'Shipped')], default='in progress', max_length=120),
        ),
    ]
