# Generated by Django 2.1.4 on 2019-02-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_auto_20190211_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipmentReturnEasyPostID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipmentReturnLabelCost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipmentReturnLabelURL',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='saleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipmentRate',
            field=models.CharField(choices=[('Priority', 'Priority'), ('ParcelSelect', 'Parcel Select'), ('Express', 'Express')], max_length=120),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipmentStatus',
            field=models.CharField(choices=[('in progress', 'Being Prepared'), ('printed', 'Printed'), ('shipped', 'Shipped')], default='in progress', max_length=120),
        ),
    ]
