# Generated by Django 2.1.4 on 2019-02-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_auto_20190213_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipmentReturnTrackingNumber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
