# Generated by Django 2.1.4 on 2019-02-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_shipment_shipmentreturntrackingnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipmentTrackingURL',
            field=models.URLField(blank=True, null=True, verbose_name='tracking url'),
        ),
    ]
