# Generated by Django 2.1.4 on 2019-02-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0012_shipment_shipmenttrackingurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipmentDateCreated',
            new_name='shipmentDateRequested',
        ),
    ]
