# Generated by Django 2.1.4 on 2019-02-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0013_auto_20190218_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipmentDateLabelPrinted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='shipment date label printed'),
        ),
    ]
