# Generated by Django 2.1.4 on 2019-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_shipment_shipmentdatelabelprinted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipmentReturnLabelURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
