# Generated by Django 2.1.4 on 2019-02-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0015_auto_20190218_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipmentFromAddress',
        ),
    ]
