# Generated by Django 2.1.7 on 2019-02-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0016_remove_shipment_shipmentfromaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipmentRate',
            field=models.CharField(choices=[('Priority', 'Priority'), ('ParcelSelect', 'Parcel Select'), ('First', 'First Class'), ('Express', 'Express')], max_length=120),
        ),
    ]
