# Generated by Django 2.1.4 on 2019-01-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0004_auto_20190130_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleID', models.AutoField(primary_key=True, serialize=False)),
                ('saleStringID', models.CharField(blank=True, max_length=120)),
                ('saleDate', models.DateTimeField(auto_now_add=True, verbose_name='sale date')),
                ('saleNote', models.CharField(default='Sale', max_length=120)),
                ('saleStatus', models.CharField(choices=[('created', 'Order created and being processed'), ('payed', 'Order payment completed and shipment being prepared'), ('shipped', 'Order has been shipped'), ('returned', 'Order was returned and has been received. Refunds will be issued upon approval'), ('refunded', 'Return was accepted and appropriate refunds have been applied')], default='created', max_length=120)),
                ('saleSubTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saleShipCostAmountCharged', models.DecimalField(decimal_places=2, default=7.0, max_digits=12)),
                ('saleTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('saleItemID', models.AutoField(primary_key=True, serialize=False)),
                ('siBasePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('siDiscountAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('siNote', models.CharField(blank=True, default='SaleItem', max_length=120)),
                ('prodStockID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.PurchaseItems')),
                ('saleID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Sale')),
            ],
            options={
                'db_table': 'sale_items',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='saleItems',
            field=models.ManyToManyField(through='sales.SaleItems', to='purchases.PurchaseItems'),
        ),
    ]
