# Generated by Django 2.1.4 on 2019-02-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_billingprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='billingProfile',
            new_name='saleBillingProfile',
        ),
    ]
