# Generated by Django 2.1.4 on 2019-02-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190203_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='siSalePrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
