# Generated by Django 2.1.4 on 2019-02-03 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitems_sisaleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='saleBillingProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='billing.BillingProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='saleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale'),
        ),
    ]
