# Generated by Django 2.1.4 on 2019-02-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190203_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='saleBillingProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
        ),
    ]
