# Generated by Django 2.1.4 on 2019-02-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_sdiscount_sdiscountcondition'),
        ('sales', '0008_auto_20190204_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='saleDiscountAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='saleDiscounts',
            field=models.ManyToManyField(to='pricing.SDiscount'),
        ),
    ]
