# Generated by Django 2.1.4 on 2019-02-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20190206_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='saleTaxAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
