# Generated by Django 2.1.4 on 2019-02-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_saletaxamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='saleDiscounts',
            field=models.ManyToManyField(blank=True, to='pricing.SDiscount'),
        ),
    ]
