# Generated by Django 2.1.4 on 2019-02-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20190211_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerShipMethod',
            fields=[
                ('cSMID', models.AutoField(primary_key=True, serialize=False)),
                ('cSMName', models.CharField(max_length=120)),
                ('cSMDescription', models.TextField(max_length=200)),
                ('cSMChargeAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'customer_ship_method',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='customerShipMethodID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.CustomerShipMethod'),
        ),
    ]
