# Generated by Django 2.1.7 on 2019-02-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20190224_0639'),
        ('sales', '0012_auto_20190211_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='salePaymentCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Card'),
        ),
    ]
