# Generated by Django 2.1.2 on 2018-11-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_description', models.CharField(max_length=200)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prod_color', models.CharField(max_length=30)),
                ('prod_categories', models.ManyToManyField(to='products.Category')),
            ],
        ),
    ]
