# Generated by Django 2.1.4 on 2019-01-10 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
                ('categoryDescription', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('categoryImageID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryImagePath', models.ImageField(upload_to='categories')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
            options={
                'db_table': 'category_image',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.CharField(max_length=200)),
                ('productCategories', models.ManyToManyField(to='products.Category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('productImageID', models.AutoField(primary_key=True, serialize=False)),
                ('productImagePath', models.ImageField(upload_to='products')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('prodStockID', models.AutoField(primary_key=True, serialize=False)),
                ('piPrice', models.DecimalField(decimal_places=3, max_digits=8)),
                ('piSize', models.CharField(max_length=200)),
                ('piColor', models.CharField(max_length=200)),
                ('piCondition', models.CharField(max_length=200)),
                ('piNotes', models.CharField(max_length=200)),
                ('piBarcode', models.ImageField(upload_to='barcodes')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateTimeField(verbose_name='date purchased')),
                ('transactionNote', models.CharField(max_length=200)),
                ('transactionStatus', models.CharField(max_length=200)),
                ('productID', models.ManyToManyField(through='products.PurchaseItems', to='products.Product')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transactionTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('transactionTypeName', models.CharField(max_length=200)),
                ('transactionTypeDescription', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'transaction_type',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorID', models.AutoField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=200)),
                ('vendorDescription', models.CharField(max_length=200)),
                ('vendorNotes', models.CharField(max_length=200)),
                ('vendorWebsite', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TransactionType'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseitems',
            name='transactionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Transaction'),
        ),
        migrations.AddField(
            model_name='purchaseitems',
            name='vendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Vendor'),
        ),
    ]
