# Generated by Django 2.1.4 on 2019-01-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSlug',
            field=models.SlugField(default='', unique=False),
            preserve_default=False,
        ),
    ]
