# Generated by Django 2.1.4 on 2019-01-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolor_productcolorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='productColorSetID',
            new_name='productColorID',
        ),
    ]
