# Generated by Django 2.1.4 on 2019-02-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190121_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productBasePrice',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productDiscountAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productSalePrice',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
