# Generated by Django 2.1.4 on 2019-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190202_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDiscountType',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSlug',
            field=models.SlugField(unique=True),
        ),
    ]
