# Generated by Django 2.1.4 on 2019-02-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190202_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDiscountValue',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
