# Generated by Django 2.1.4 on 2019-02-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_productdiscountvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='productColorName',
            field=models.CharField(max_length=120),
        ),
    ]
